site:
    title: "ðŸŽ€  /  L I L A H"
    subtitle: "Another devblog"
    limit: 10
    theme: theme
    lang: en
    url: "https://xxami.github.io/"
    # comment: username
    logo: "-/images/avatar.png"
    # link: "{category}/{year}/{month}/{day}/{title}.html"
    # root: "/blog"

authors:
    me:
        name: "Ë¡ á¶¦ Ë¡ áµƒ Ê°"
        intro: "Some text"
        avatar: "-/images/avatar.png"

build:
    output: "docs"
    port: 8000
    # Copied files to public folder when build
    copy:
        - "source/images"
    # Excuted command when use 'ink publish'
    publish: |
        git add . -A
        git commit -m "update"
        git push origin
